language: node_js
node_js:
- node
cache: npm
before_script: npm i -g now
script: npm run deploy
after_script: npm run alias
env:
  global:
  - secure: LbIQ22f2XG/DBtFWnLjbb3m/dAhjkAsZ5hcD04DGQgbVtPovikze0qcFqleS60qMRKONOFJwAe+e40JX71rlTc2u1ZjPaeuAJxgoC4q8/9b1M0sZkF/RWLy1zNTDAAlrzP2uulvW74nN6AMLuZX8vkzgd5+fpVyD+iRFSFK3mSxJ4HvFYgSn6KqZE5dt/QnktdLrJqhWPAaXeVE4xc7M40HI6Ke+sm2VOeNBfrOOZpJzTa6Qyt9l9GcPZS25YvaLN+i9qJ34O7/5oaDOg8mJ/LJGyXCLnl0t/lgiqPGRpTc/y9kZSYhs2bapEstt1y7RzGX8+f2phgwXaRo7s/bRLgS5ltkjfgU1uBkTy3edxkJqGdmnbfrLDZbbHmdzNTAC3zGkf1ELdo0F7Z0ZcaWWhZN5WEUYRsye3xGaf2nchmE+rz7idjzh8QJgYy3Kl5F2Ws1pMOrTXezh7kyUI6zJBScFwi2WDsD9Zuo3kk2/7eLxVqsH+VKFlitCZAb1zbdYr/dFKe4aHt32lp94LsEM3DwvYAuCFWhpuyF6Yp7b3pZeEVMGidXM4sPDnOe744YO/fQBFkqX7qBHyKBVRxkihUG3g4gd6jeHgjqacYFk2FnXldqbLfk3tblwgMFMwRya7rfgAxGsxIut/S5BvH8OiV5X1iLyI+cyWoy373FJPTM=
